env: 
  global: 
  - secure: ogs/6I/ibgGyUvw0t33vhV+8aqke/edkGUDASByYhlyvusY3y2yLwISK26kZ55MZ0k2tZWi/TFgYfNTudD5XXo6c5iOFtW8S7EdmJ0+a8+F1ZBw71ed67kuEsT5dT0oaeG63VdS0Nq1GQT7yp+hMXDDs6LOKhDd0xQ/eThj8Bhs=
  - secure: LZmjLOz8wuWW3s98BAIR2v7u9Ip44XnTDglD/wYf3Op3TZhqUqkMscUkGnA3BH9dYU/BTLyxCI+F4/hkIQJFAwE+NT3dYp+L7+DCD91/7jy55j7QYAYG+gjA38YioKGLsgFhejVkbqAw/hYXj3zgcMHOCfacQMRxCvxd24bQ5T8=
before_script: 
- npm install -g grunt-cli
- git submodule update --init --recursive
script:
- npm test
- npm run-script saucelabs-test
node_js: 
- 0.1
branches: 
  only: 
  - master
  - gh-pages
language: node_js
