language: node_js
node_js:
  - "0.12"
sudo: false
branches:
  only:
  - master
  - gh-pages
addons:
  sauce_connect:
    username: "bladerunnerjs"
    access_key:
      secure: "DT8qKtDFm7Jh4uBd1SYF1HwOjqRUQbFsngo6aaief1rfWmZtcdlbZjIvdPm39KbMUC6g8YiHHxjGwJL7ieCSdK/cmv/RumEIALU6xxCTo6MVOgSEb7YhLGeRxmx9ahrXEmhCTkMIFsjD9Gj7VOq2+DIZuR72ZXQirg21ji1SD/Q="
