language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm test
  - npm run test:saucelabs
branches:
  only:
    - master
    - gh-pages
